export const EVENT_SCHEDULER_IMPORT_EVENTS_FLAG = 'MMS_SCHEDULER--import-events';
export const EVENT_SCHEDULER_EXPORT_EVENTS_FLAG = 'MMS_SCHEDULER--export-events';
export const EVENT_SCHEDULER_CREATE_EVENTS_FLAG = 'MMS_SCHEDULER--create-events';
export const EVENT_SCHEDULER_UPDATE_EVENTS_FLAG = 'MMS_SCHEDULER--update-events';
export const EVENT_SCHEDULER_UPDATE_EVENT_STATES_FLAG = 'MMS_SCHEDULER--update-event-states';
export const EVENT_SCHEDULER_BANANA_TEST = 'MMS_SCHEDULER--banana-test ';
