name: 'Jest coverage report'
on:
    pull_request:
        branches:
            - develop
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Upload Coverage Report
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                github-token: ${{ secrets.GH_TOKEN }}
                package-manager: yarn
                annotations: none

